---
title: 'OTU clustering at 99%'
author: "B. K. Montero and M. Gillingham"
date: "`r Sys.Date()`"
output: html_document
---

## LOAD LIBRARIES


```{r loadLibraries, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

rm(list = ls())

# basics
library(stringr)
library(dplyr)
library(tidyr)
library(magrittr)
library(data.table)
library(ggplot2)
library(ggpubr)
library(tibble)

# phyloseq section
library(phyloseq)
library(Biostrings)
library(DECIPHER)
library(speedyseq)
library(metagMisc)
library(seqateurs)

```


## WORKING DIRECTORIES
```{r source, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE, results="hide"}

source("~/Dropbox/FringillaMicrobiome/05_Scripts/workingDirectories.R")

```

## LOAD DATA

### 1. Clean phyloseq object

```{r cleanPS, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}
ps_ASV_rarefied <- readRDS(paste0(dataDir, "/ps_ASV_rarefied.rds" ))
ps_ASV_rarefied

```

### 2. Tables
```{r tables, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

seqtab <- otu_table(ps_ASV_rarefied)
asv_sequences <- colnames(seqtab)
#sample_names <- rownames(seqtab)

class(seqtab)

```

### 3. Alignment

```{r alignm, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE, echo=FALSE, eval=FALSE}

# set to number of cpus/processors to use for the clustering
nproc <- 16

dna <- readDNAStringSet(file = paste0(dataDir, "/ps_ASV_rarefied.fasta"), format = "fasta", nrec = -1L, skip = 0L, seek.first.rec = FALSE,  use.names = TRUE)

aln <- DECIPHER::AlignSeqs(dna, processors = nproc)

#saveRDS(aln, paste0(dataDir, "/ASV_rarefied_alnDecipher.rds"))
#aln <- readRDS(paste0(dataDir, "/ASV_rarefied_alnDecipher.rds"))

```

## CLUSTER

Run in cluster
```{r cluster, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE, echo=FALSE, eval=FALSE}

d <- DECIPHER::DistanceMatrix(aln, processors = nproc, type = "matrix")
#d_matrix <- as.matrix(d)
#class(d_matrix)

clusters <- DECIPHER::TreeLine(myDistMatrix = d, method = "complete", cutoff = 0.01, processors = nproc, type="clusters") # use `cutoff = 0.01` for a 99% OTU 

head(clusters)
clusters <- clusters %>%
  add_column(sequence = asv_sequences)
head(clusters)

merged_seqtab <- seqtab %>% 
  t %>%
  rowsum(clusters$cluster) %>%
  t

# Rename clusters to OTU
colnames(merged_seqtab) <- paste0("OTU", colnames(merged_seqtab))
str(merged_seqtab)
#saveRDS(clusters, paste0(dataDir, "/clusters_", Sys.Date(), ".rds"))
#saveRDS(merged_seqtab, paste0(dataDir, "/merged_seqtab_", Sys.Date(), ".rds"))


```

Load OTU objects 
```{r otuObj, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

clusters <- readRDS(paste0(dataDir, "/clusters_2024-10-28.rds"))
merged_seqtab <- readRDS(paste0(dataDir, "/merged_seqtab_2024-10-28.rds"))
str(clusters)

```

## OTU PS OBJECT

Replace ASVs with OTUs in ps_ASV_rarefied object 

```{r otuPS, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

ps_OTU_99 <- merge_taxa_vec(
  ps_ASV_rarefied, 
  group = clusters$cluster,
  tax_adjust = 1
)
tax_table(ps_OTU_99) <- tax_table(ps_OTU_99)[,1:7]
tax_table(ps_OTU_99)
ps_OTU_99

# make sure there is no unclassified phyla, mitochondria and chloroplast

ps_OTU_99_clean  <- ps_OTU_99 %>%
  subset_taxa(Kingdom == "Bacteria" & Phylum != "NA" & !Phylum %in% c("", "uncharacterized"))

ps_OTU_99_clean  <- ps_OTU_99_clean  %>% subset_taxa(Order != "Chloroplast" & Order != "Mitochondria" & Family != "Mitochondria" & Family != "Chloroplast" & Genus != "Chloroplast" & Genus != "Mitochondria"| is.na(Order) | is.na(Family) | is.na(Genus))

ps_OTU_99_clean 
tax_table(ps_OTU_99_clean)

# Rename ASVs
taxa_names(ps_OTU_99_clean) <- paste0("OTU", seq(ntaxa(ps_OTU_99_clean)))

# add ASV and ASV_SEQ columns to taxonomy table
tax_table(ps_OTU_99_clean) <- cbind(tax_table(ps_OTU_99_clean), 
    rownames(tax_table(ps_OTU_99_clean)))
colnames(tax_table(ps_OTU_99_clean)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "OTU_ID")
```


Estimate OTU alpha

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

OTU_alpha <- estimate_richness(ps_OTU_99_clean, measures=c("Observed","Shannon"))
sample_data(ps_OTU_99_clean)$Observed_OTU_rare <- OTU_alpha$Observed
sample_data(ps_OTU_99_clean)$Shannon_OTU_rare <- OTU_alpha$Shannon
sample_data(ps_OTU_99_clean) %>% data.frame %>% head

```

Update phyloseq objects

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

# Update microbiome object
sample_data(ps_ASV_rarefied)$Observed_OTU_rare <- OTU_alpha$Observed
sample_data(ps_ASV_rarefied)$Shannon_OTU_rare <- OTU_alpha$Shannon

# TipId as sample names 
sample_data(ps_ASV_rarefied)$Species_Label <- gsub(" ", "_", sample_data(ps_ASV_rarefied)$Species_Label)
sample_names(ps_ASV_rarefied) <- paste(sample_data(ps_ASV_rarefied)$Lab_Code, sample_data(ps_ASV_rarefied)$Species_Label, sep = "_")

sample_data(ps_OTU_99_clean)$Species_Label <- gsub(" ", "_", sample_data(ps_OTU_99_clean)$Species_Label)
sample_names(ps_OTU_99_clean) <- paste(sample_data(ps_OTU_99_clean)$Lab_Code, sample_data(ps_OTU_99_clean)$Species_Label, sep = "_")


# Fringilla subsets
ps_ASV_rarefied_fr <- ps_ASV_rarefied %>% subset_samples(Genus == "Fringilla")
ps_OTU_99_clean_fr <- ps_OTU_99_clean %>% subset_samples(Genus == "Fringilla")


# Remove Zeros
library(biomeUtils)
ps_ASV_rarefied_fr <- removeZeros(ps_ASV_rarefied_fr)
ps_OTU_99_clean_fr <- removeZeros(ps_OTU_99_clean_fr)


ps_OTU_99_clean_fr %>% sample_data %>% data.frame %>% head(3)

```

Export filtered OTU fasta 

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

ps_to_fasta(ps_OTU_99_clean_fr, out.file = paste0(dataDir, "/OTU_99_clean_fr.fasta"), width = 1800, seqnames = "OTU_ID")

```

Build tree

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

conda activate qiime2-amplicon-2024.5      
cd ~/Dropbox/FringillaMicrobiome/07_Data/

  
qiime tools import \
  --type 'FeatureData[Sequence]' \
  --input-path OTU_99_clean_fr.fasta \
  --output-path OTU_99_clean_fr.qza


qiime phylogeny align-to-tree-mafft-iqtree \
  --i-sequences OTU_99_clean_fr.qza \
  --p-n-threads 'auto' \
  --p-mask-max-gap-frequency 0.9 \
  --o-alignment ~/Dropbox/FringillaMicrobiome/07_Data/OTU_99_clean_fr.qza \
  --o-masked-alignment ~/Dropbox/FringillaMicrobiome/07_Data/OTU_99_clean_fr_aln.qza \
  --o-tree ~/Dropbox/FringillaMicrobiome/07_Data/OTU_99_clean_fr_unrooted.treefile \
  --o-rooted-tree ~/Dropbox/FringillaMicrobiome/07_Data/OTU_99_clean_fr_rooted.treefile \
  --output-dir ~/Dropbox/FringillaMicrobiome/07_Data/qiimetree 

```

merge tree

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

# import tree 
tree <- read_tree(paste0(dataDir, "/OTU_99_clean_fr_rooted.tre.nwk"))

ps_OTU_99_clean_fr <- merge_phyloseq(ps_OTU_99_clean_fr,tree)
ps_OTU_99_clean_fr

```

Overlap with diet dataset

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

diet_rare <- readRDS(paste0(dataDir, "/diet_overlap_ASV_rare_fr.rds"))

sample_data(diet_rare) %>% data.frame %>% names

diet_alpha <- estimate_richness(diet_rare, measures=c("Observed","Shannon"))

sample_data(diet_rare)$Observed_diet_rare <- diet_alpha$Observed
sample_data(diet_rare)$Shannon_diet_rare <- diet_alpha$Shannon

ps_OTU_99_clean_fr%>% sample_data %>% names
diet_rare %>% sample_data %>% names

sample_names(ps_OTU_99_clean_fr)
sample_names(diet_rare)

setdiff(sample_names(ps_OTU_99_clean_fr), sample_names(diet_rare)) %>% print
setdiff(sample_names(diet_rare), sample_names(ps_OTU_99_clean_fr)) %>% print


# overlap
microb_overlap_rare_fr <- prune_samples(sample_names(ps_OTU_99_clean_fr) %in% sample_names(diet_rare), ps_OTU_99_clean_fr) 

diet_overlap_rare_fr <- prune_samples(sample_names(diet_rare) %in% sample_names(ps_OTU_99_clean_fr), diet_rare) 

sample_names(microb_overlap_rare_fr) == sample_names(diet_overlap_rare_fr)

# add diet diversity estimates to microbiome data

sample_data(microb_overlap_rare_fr)$Observed_diet_rare <- sample_data(diet_overlap_rare_fr)$Observed_diet_rare
sample_data(microb_overlap_rare_fr)$Shannon_diet_rare <- sample_data(diet_overlap_rare_fr)$Shannon_diet_rare
sample_data(microb_overlap_rare_fr)$E <- sample_data(diet_overlap_rare_fr)$E
sample_data(microb_overlap_rare_fr)$VarE <- sample_data(diet_overlap_rare_fr)$VarE


microb_overlap_rare_fr %>% sample_data %>% names
diet_rare %>% sample_data %>% names

microb_overlap_rare <- removeZeros(microb_overlap_rare)
diet_overlap_rare <- removeZeros(diet_overlap_rare)
microb_overlap_rare_fr <- removeZeros(microb_overlap_rare_fr)
diet_overlap_rare_fr <- removeZeros(diet_overlap_rare_fr)
```


Update phyloseq objects 

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

# Update diet object
diet_overlap_rare_fr <- readRDS(paste0(dataDir, "/diet_overlap_ASV_rare_fr.rds"))

sample_data(diet_overlap_rare_fr) %>% data.frame %>% names

diet_alpha <- estimate_richness(diet_overlap_rare_fr, measures=c("Observed","Shannon"))

sample_data(diet_overlap_rare_fr)$Observed_diet_rare <- diet_alpha$Observed
sample_data(diet_overlap_rare_fr)$Shannon_diet_rare <- diet_alpha$Shannon


ps_ASV_rarefied %>% sample_data %>% names
ps_diet_rarefied %>% sample_data %>% names

setdiff(sample_names(ps_ASV_rarefied), sample_names(ps_OTU_99_clean)) %>% print

# Update 16S object

microb_overlap_rare_fr <- prune_samples(sample_names(ps_OTU_99_clean_fr) %in% sample_names(diet_overlap_rare_fr), ps_OTU_99_clean_fr) 
setdiff(sample_names(diet_overlap_rare_fr), sample_names(microb_overlap_rare_fr)) %>% print
setdiff(sample_names(microb_overlap_rare_fr), sample_names(diet_overlap_rare_fr)) %>% print

microb_overlap_rare_fr %>% sample_data %>% data.frame %>% head
sample_data(diet_overlap_rare_fr)$Observed_OTU_rare <- sample_data(microb_overlap_rare_fr)$Observed_OTU_rare
sample_data(diet_overlap_rare_fr)$Shannon_OTU_rare <- sample_data(microb_overlap_rare_fr)$Shannon_OTU_rare

sample_names(microb_overlap_rare_fr) == sample_names(diet_overlap_rare_fr)

microb_overlap_rare_fr <- removeZeros(microb_overlap_rare_fr)
diet_overlap_rare_fr <- removeZeros(diet_overlap_rare_fr)


```

Save output

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

### All species

# ASV phyloseq with ASV and OTU alpha estimates
saveRDS(ps_ASV_rarefied, paste0(dataDir, "/ps_ASV_rare_wAlpha.rds"))

# OTU phyloseq with ASV and OTU alpha estimates
saveRDS(ps_OTU_99_clean, paste0(dataDir, "/ps_OTU99_wAlpha.rds"))

###  Fringilla subsets

# ASV phyloseq with ASV and OTU alpha estimates
saveRDS(ps_ASV_rarefied_fr, paste0(dataDir, "/ps_ASV_rare_wAlpha_fr.rds"))

# OTU phyloseq with ASV and OTU alpha estimates
saveRDS(ps_OTU_99_clean_fr, paste0(dataDir, "/ps_OTU99_wAlpha_fr.rds"))

# OTU phyloseq overlap diet with ASV and OTU alpha estimates
saveRDS(microb_overlap_rare_fr, paste0(dataDir, "/microb_overlap_OTU99_fr.rds"))

# diet phyloseq overlap 16S with ASV and OTU alpha estimates
saveRDS(diet_overlap_rare_fr, paste0(dataDir, "/diet_overlap_OTU99_fr.rds"))

```

## Session Info

```{r, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}
sessioninfo::session_info()%>%
  details::details(summary = 'Current session info', open = FALSE)
```