---
title: 'Ordination diet'
author: "B. Karina Montero and Mark Gillingham"
date: "`r Sys.Date()`"
output: 
  rmdformats::downcute:
    code_folding: hide
    toc_depth: 2
---

## LOAD LIBRARIES

```{r libraries, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE, results="hide"}

rm(list = ls())

# basics
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
library(tidyverse)

# phyloseq + diversity
library(phyloseq)
library(biomeUtils)
library(microbiome)
library(vegan)

```

## WORKING DIRECTORIES

```{r workingDir, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE, results="hide"}

source("~/Dropbox/FringillaMicrobiome/05_Scripts/workingDirectories.R")
source("~/Dropbox/FringillaMicrobiome/05_Scripts/CleanScripts/graphics_param.R")

```

## LOAD DATA

```{r psObject, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

diet_fr <- readRDS(paste0(dataDir, "/diet_fr_corrected.rds")) %>%
  subset_samples(Genus == "Fringilla")

# Standardise label format
sample_data(diet_fr)$Species_Label <- gsub(" ", "_", sample_data(diet_fr)$Species_Label)

# Remove samples with only 1 ASV (Lab_Codes 306 and 105)
diet_filt <- diet_fr %>%
  subset_samples(!Lab_Code %in% c("306", "105")) %>%
  removeZeros()

# Shared factor level definition for ordination panels
species_levels <- c("El_Hierro_F_c_ombriosa", "Flores_F_moreletti",
                    "Gran_Canaria_F_c_bakeri", "Gran_Canaria_F_polatzeki",
                    "La_Gomera_F_c_canariensis", "La_Palma_F_c_palmae",
                    "Madeira_F_maderensis", "Mainland_F_coelebs",
                    "Sao_Miguel_F_moreletti", "Tenerife_F_c_canariensis",
                    "Tenerife_F_teydea")

species_labels_parsed <- c(
  "El~Hierro:~italic('F.c. ombriosa')", "Flores:~italic('F. moreletti')",
  "Gran~Canaria:~italic('F.c. bakeri')", "Gran~Canaria:~italic('F. polatzeki')",
  "La~Gomera:~italic('F.c. canariensis')", "La~Palma:~italic('F.c. palmae')",
  "Madeira:~italic('F. maderensis')", "Mainland:~italic('F. coelebs')",
  "Sao~Miguel:~italic('F. moreletti')", "Tenerife:~italic('F.c. canariensis')",
  "Tenerife:~italic('F. teydea')")

```

## NMDS ORDINATIONS

```{r nmds, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

# Helper that builds an NMDS plot for a given distance method
build_nmds_plot <- function(ps, distance, binary, seed = 1, ord_args = list()) {
  set.seed(seed)
  
  if (distance == "raupcrick") {
    rc_dist <- raupcrick(otu_table(ps))
    ord <- do.call(metaMDS, c(list(comm = rc_dist), ord_args))
  } else {
    ord <- do.call(metaMDS,
                   c(list(comm = otu_table(ps), distance = distance, binary = binary),
                     ord_args))
  }
  
  scrs <- scores(ord, display = 'sites') %>%
    as.data.frame() %>%
    mutate(Species_Label = sample_data(ps)$Species_Label)
  
  cent <- aggregate(cbind(NMDS1, NMDS2) ~ Species_Label, data = scrs, FUN = mean)
  
  ggplot(scrs, aes(x = NMDS1, y = NMDS2, fill = Species_Label, shape = Species_Label)) +
    geom_point(alpha = 1, size = 10, stroke = 1.5, color = "white") +
    geom_point(data = cent, aes(y = NMDS2, x = NMDS1, fill = Species_Label),
               size = 17, stroke = 1.5, color = "black") +
    pca_theme + SpeciesLabel.fill +
    scale_shape_manual(values = c(21, 22, 23, 21, 23, 25, 21, 21, 21, 22, 25), guide = "none") +
    guides(color = "none")
}

# Jaccard
jaccard_NMDS <- build_nmds_plot(diet_filt, "jaccard", binary = TRUE, seed = 100)
png(paste0(outputDir, "/Figures/Jaccard_NMDS_diet_PCH_clean.png"),
    width = 320, height = 240, units = "mm", res = 1000)
print(jaccard_NMDS); dev.off()

# Bray-Curtis
bray_NMDS <- build_nmds_plot(diet_filt, "bray", binary = FALSE, seed = 1)
png(paste0(outputDir, "/Figures/bray_NMDS_diet_PCH_clean.png"),
    width = 320, height = 240, units = "mm", res = 1000)
print(bray_NMDS); dev.off()

# Raup-Crick
raupcrick_NMDS <- build_nmds_plot(diet_filt, "raupcrick", binary = NA, seed = 1)
png(paste0(outputDir, "/Figures/raupcrick_NMDS_diet_PCH_clean.png"),
    width = 320, height = 240, units = "mm", res = 1000)
print(raupcrick_NMDS); dev.off()

```

## TEST EFFECT OF SEX AND AGE (PERMANOVA)

```{r permanova, message=FALSE, warning=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=45), paged.print=FALSE}

# Create age category
sample_data(diet_filt)$Age_cat <- ifelse(sample_data(diet_filt)$Age > 3, "adult", "fledging")

# Keep only samples with non-missing age and sex
diet_clean_noNA <- diet_filt %>%
  subset_samples(Genus == "Fringilla" & Age > 0 & !is.na(Sex)) %>%
  removeZeros()

# Helper that runs PERMANOVA for a given distance metric
run_permanova <- function(ps, dist_method, binary = FALSE, seed = 42) {
  if (dist_method == "raupcrick") {
    d <- raupcrick(otu_table(ps))
  } else {
    d <- vegdist(otu_table(ps), method = dist_method, binary = binary)
  }
  set.seed(seed)
  adonis2(d ~ Species_Label + Age_cat + Sex,
          data = meta(ps), by = "margin", permutations = 9999)
}

ad_jac  <- run_permanova(diet_clean_noNA, "jaccard", binary = TRUE)
ad_bray <- run_permanova(diet_clean_noNA, "bray",    binary = FALSE)
ad_rc   <- run_permanova(diet_clean_noNA, "raupcrick")

ad_jac
ad_bray
ad_rc

```